### ISSUE TITLE
Clock running too fast

### ISSUE THREAD

**Issue by HansDaigle** [cipchk/ngx-countdown#36]
<pre><code>
[X ] Bug report -> please search issues before submitting
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior
The clock seconds are changing too fast when updating the `lefttime` in NgOnChanges, almost twice as fast as a normal clock.

## Environment
Ubuntu 18

This is my current code:

html:

```
<countdown [config]="{leftTime: second_left,
                      clock: ['d', 100, 2, 'h', 24, 2, 'm', 60, 2, 's', 60, 2, 'u', 10, 1] }">$!d!d $!h!h $!m!m $!s!s</countdown>
```

.ts:
```
import {Component, Input, OnChanges, SimpleChanges} from '@angular/core';

@Component({
  selector: 'app-countdown',
  templateUrl: './countdown.component.html',
  styleUrls: ['./countdown.component.css']
})
export class CountdownComponent implements OnChanges {
    @Input() string_date;
    second_left = 0;

  constructor() { }

    ngOnChanges(changes: SimpleChanges) {
        if (changes.string_date.currentValue) {
            const date_to = new Date(this.string_date);
            const dif = date_to.getTime() - Date.now();
            this.second_left = dif / 1000;       // second left before or after the date
            console.log(this.second_left);
        }
  }
}

```

**Comment by HansDaigle** [comment]
Resolved by casting the `lefttime` value to a String. This librairy dosent do well with floats

**Comment by pradeep8093** [comment]
I am too facing the same issue.

Any help?

**Comment by bijanmmarkes** [comment]
@HansDaigle @pradeep8093 - This issue is related to how the timer gets initialized. If it gets initialized at `leftTime: 0` or `empty` then it will automatically start counting down 2-3x faster rather than per second, I'm not sure why this issue occurs nor do I feel like finding out, but it does.

Solution:
Initialize the countdown timer config using a `leftTime` value of `1` or greater. 

This may not be desired as the user may see it countdown from 1 to 0 until you want to `officially` start it, but a workaround is to have it not display until the first time it is stopped (after the initial 1 second). Another option is to not show the timer until you want to officially start it.
