### ISSUE TITLE
timeLeft <= 0 sets timer to 23:59:59

### ISSUE THREAD

**Issue by cubitt-nottscc** [cipchk/ngx-countdown#43]
## Bug Report or Feature Request (mark with an `x`)
<pre><code>
[x ] Bug report -> please search issues before submitting
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior
When timeLeft argument is 0 or negative, countdown rolls around to 23:59:59.

Previous version would stay at 00:00:00.

## Expected behavior
Countdown stays at 00:00:00

## Environment

<pre><code>
Angular version: 8.3.2

ngx-countdown version: 8.0.0

Browser:
- [x ] Chrome (desktop) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX

Others:

</code></pre>
Example here:
https://stackblitz.com/edit/ngx-countdown-setup-nde9pq

**Comment by aronlundgren** [comment]
did you find any workaround for this?

**Comment by cipchk** [comment]
@cubitt-nottscc @aronlundgren fix by `8.0.1`

**Comment by DaveOdden** [comment]
When the timer ends, in 8.0.1, The value changes to all zeros. However, if a value exists in the past when this component is initialized, this bug exists. I am *attempting* to use this component to show a countdown for events at a fundraiser and am running into a ton of unexpected behavior. I am having to compare the current date `new Date().getTIme()` to the countdown's date/time in order to set the `stopTime` property of the configuration to 0 if it exists in the past
